/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;
import compilador.*;
import java.util.StringTokenizer;


/**
 *
 * @author saravera
 */
public class Calculadora extends javax.swing.JFrame {
    
    public String cadenaNumeros = "";
    public String cadenaAnalisis = "";
   
    public boolean activado = true;
    
    static Compilador comp;

    /**
     * Creates new form Calculadora
     */
    public Calculadora() throws ErrorDeSintaxisException,ErrorAritmeticoException {
        initComponents();
        this.setTitle("Calculadora");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        botonC = new javax.swing.JButton();
        botonRaiz = new javax.swing.JButton();
        botonDivision = new javax.swing.JButton();
        botonCE = new javax.swing.JButton();
        botonSen = new javax.swing.JButton();
        botonCos = new javax.swing.JButton();
        botonTan = new javax.swing.JButton();
        botonMultiplicar = new javax.swing.JButton();
        boton7 = new javax.swing.JButton();
        boton8 = new javax.swing.JButton();
        boton9 = new javax.swing.JButton();
        botonResta = new javax.swing.JButton();
        boton4 = new javax.swing.JButton();
        boton5 = new javax.swing.JButton();
        boton6 = new javax.swing.JButton();
        botonSumar = new javax.swing.JButton();
        boton1 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        botonParenDer = new javax.swing.JButton();
        botonPunto = new javax.swing.JButton();
        boton0 = new javax.swing.JButton();
        botonParenIzq = new javax.swing.JButton();
        botonIgual = new javax.swing.JButton();
        etiquetaNumeros = new javax.swing.JLabel();
        etiquetaMuestra = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setLayout(new java.awt.GridLayout(6, 4));

        botonC.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        botonC.setText("C");
        botonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCActionPerformed(evt);
            }
        });
        panel.add(botonC);

        botonRaiz.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        botonRaiz.setText("√ ");
        botonRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRaizActionPerformed(evt);
            }
        });
        panel.add(botonRaiz);

        botonDivision.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        botonDivision.setText("÷");
        botonDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDivisionActionPerformed(evt);
            }
        });
        panel.add(botonDivision);

        botonCE.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        botonCE.setText("CE");
        botonCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCEActionPerformed(evt);
            }
        });
        panel.add(botonCE);

        botonSen.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        botonSen.setText("sen");
        botonSen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSenActionPerformed(evt);
            }
        });
        panel.add(botonSen);

        botonCos.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        botonCos.setText("cos");
        botonCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCosActionPerformed(evt);
            }
        });
        panel.add(botonCos);

        botonTan.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        botonTan.setText("tan");
        botonTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTanActionPerformed(evt);
            }
        });
        panel.add(botonTan);

        botonMultiplicar.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        botonMultiplicar.setText("x");
        botonMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMultiplicarActionPerformed(evt);
            }
        });
        panel.add(botonMultiplicar);

        boton7.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        boton7.setText("7");
        boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton7ActionPerformed(evt);
            }
        });
        panel.add(boton7);

        boton8.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        boton8.setText("8");
        boton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton8ActionPerformed(evt);
            }
        });
        panel.add(boton8);

        boton9.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        boton9.setText("9");
        boton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton9ActionPerformed(evt);
            }
        });
        panel.add(boton9);

        botonResta.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        botonResta.setText("-");
        botonResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRestaActionPerformed(evt);
            }
        });
        panel.add(botonResta);

        boton4.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        boton4.setText("4");
        boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton4ActionPerformed(evt);
            }
        });
        panel.add(boton4);

        boton5.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        boton5.setText("5");
        boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton5ActionPerformed(evt);
            }
        });
        panel.add(boton5);

        boton6.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        boton6.setText("6");
        boton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton6ActionPerformed(evt);
            }
        });
        panel.add(boton6);

        botonSumar.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        botonSumar.setText("+");
        botonSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSumarActionPerformed(evt);
            }
        });
        panel.add(botonSumar);

        boton1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        boton1.setText("1");
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });
        panel.add(boton1);

        boton2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        boton2.setText("2");
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });
        panel.add(boton2);

        boton3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        boton3.setText("3");
        boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton3ActionPerformed(evt);
            }
        });
        panel.add(boton3);

        botonParenDer.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        botonParenDer.setText(")");
        botonParenDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonParenDerActionPerformed(evt);
            }
        });
        panel.add(botonParenDer);

        botonPunto.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        botonPunto.setText(".");
        botonPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPuntoActionPerformed(evt);
            }
        });
        panel.add(botonPunto);

        boton0.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        boton0.setText("0");
        boton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton0ActionPerformed(evt);
            }
        });
        panel.add(boton0);

        botonParenIzq.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        botonParenIzq.setText("(");
        botonParenIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonParenIzqActionPerformed(evt);
            }
        });
        panel.add(botonParenIzq);

        botonIgual.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        botonIgual.setText("=");
        botonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try{
                botonIgualActionPerformed(evt);
                }catch(Exception e){
                    etiquetaNumeros.setText(e.getMessage());
                }

            }
        });
        panel.add(botonIgual);

        etiquetaNumeros.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        etiquetaNumeros.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaNumeros.setText("0");

        etiquetaMuestra.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        etiquetaMuestra.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etiquetaMuestra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiquetaNumeros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaMuestra, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(etiquetaNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Método que representa el boton que borra el último dígito.

    private void botonCActionPerformed(java.awt.event.ActionEvent evt){
        //etiquetaNumeros.setTex("0");
        cadenaNumeros = "";
        cadenaAnalisis = "";
        activado = true;//GEN-FIRST:event_botonCActionPerformed
        etiquetaNumeros.setText("0");
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCActionPerformed

    //Método que representa el boton del número 6

    private void boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton6ActionPerformed
       if(etiquetaNumeros.getText().equals("0")){
           cadenaNumeros = "6";
           cadenaAnalisis = "6";
       }else{
             cadenaNumeros += "6";
             cadenaAnalisis += "6";
       }
         etiquetaNumeros.setText(cadenaNumeros);
         activado = true;// TODO add your handling code here:
    }//GEN-LAST:event_boton6ActionPerformed

    //Método que representa el boton del número 3
    private void boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton3ActionPerformed
        if(etiquetaNumeros.getText().equals("0")){
           cadenaNumeros = "3";
           cadenaAnalisis = "3";
       }else{
             cadenaNumeros += "3";
             cadenaAnalisis += "3";
       }
         etiquetaNumeros.setText(cadenaNumeros);
         activado = true;// TODO add your handling code here:
    }//GEN-LAST:event_boton3ActionPerformed

    //Método que representa el boton del número 4
    private void boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton4ActionPerformed
        if(etiquetaNumeros.getText().equals("0")){
           cadenaNumeros = "4";
           cadenaAnalisis = "4";
       }else{
             cadenaNumeros += "4";
             cadenaAnalisis += "4";
       }
         etiquetaNumeros.setText(cadenaNumeros);
         activado = true ;// TODO add your handling code here:
    }//GEN-LAST:event_boton4ActionPerformed

    //Método que representa el boton del número 7
    private void boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton7ActionPerformed
        if(etiquetaNumeros.getText().equals("0")){
           cadenaNumeros = "7";
           cadenaAnalisis = "7";
       }else{
             cadenaNumeros += "7";
             cadenaAnalisis += "7";
       }
         etiquetaNumeros.setText(cadenaNumeros);
         activado = true;// TODO add your handling code here:
    }//GEN-LAST:event_boton7ActionPerformed

    //Método que representa el boton del número 8
    private void boton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton8ActionPerformed
        if(etiquetaNumeros.getText().equals("0")){
           cadenaNumeros = "8";
           cadenaAnalisis = "8";
       }else{
             cadenaNumeros += "8";
             cadenaAnalisis += "8";
       }
         etiquetaNumeros.setText(cadenaNumeros);
         activado = true;// TODO add your handling code here:
    }//GEN-LAST:event_boton8ActionPerformed

    //Método que representa el boton del número 9
    private void boton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton9ActionPerformed
        if(etiquetaNumeros.getText().equals("0")){
           cadenaNumeros = "9";
           cadenaAnalisis = "9";
       }else{
             cadenaNumeros += "9";
             cadenaAnalisis += "9";
       }
         etiquetaNumeros.setText(cadenaNumeros);
         activado = true;// TODO add your handling code here:
    }//GEN-LAST:event_boton9ActionPerformed

    //Método que representa el boton del número 5
    private void boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton5ActionPerformed
        if(etiquetaNumeros.getText().equals("0")){
           cadenaNumeros = "5";
           cadenaAnalisis = "5";
       }else{
             cadenaNumeros += "5";
             cadenaAnalisis += "5";
       }
         etiquetaNumeros.setText(cadenaNumeros);
         activado = true;// TODO add your handling code here:
    }//GEN-LAST:event_boton5ActionPerformed

    //Método que representa el boton del número 1
    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        if(etiquetaNumeros.getText().equals("0")){
           cadenaNumeros = "1";
           cadenaAnalisis = "1";
       }else{
             cadenaNumeros += "1";
             cadenaAnalisis += "1";
       }
         etiquetaNumeros.setText(cadenaNumeros);
         activado = true;// TODO add your handling code here:
    }//GEN-LAST:event_boton1ActionPerformed

    //Método que representa el boton del número 2
    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
        if(etiquetaNumeros.getText().equals("0")){
           cadenaNumeros = "2";
           cadenaAnalisis = "2";
       }else{
             cadenaNumeros += "2";
             cadenaAnalisis += "2";
       }
         etiquetaNumeros.setText(cadenaNumeros);
         activado = true;// TODO add your handling code here:
    }//GEN-LAST:event_boton2ActionPerformed

    //Método que representa el boton del número 0
    private void boton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton0ActionPerformed
        if(etiquetaNumeros.getText().equals("0")){
           cadenaNumeros = "0";
           cadenaAnalisis = "0";
       }else{
             cadenaNumeros += "0";
             cadenaAnalisis += "0";
       }
         etiquetaNumeros.setText(cadenaNumeros);
         activado = true;// TODO add your handling code here:
    }//GEN-LAST:event_boton0ActionPerformed

    //Método que representa el boton del operador +
    private void botonSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSumarActionPerformed
       if(etiquetaNumeros.getText().equals("0")){
           cadenaNumeros = "+";
           cadenaAnalisis = "+";
       }else{
             cadenaNumeros += "+";
             cadenaAnalisis += "+";
       }
         etiquetaNumeros.setText(cadenaNumeros);
         activado = true; // TODO add your handling code here:
    }//GEN-LAST:event_botonSumarActionPerformed

    //Método que representa el boton del operador =
    private void botonIgualActionPerformed(java.awt.event.ActionEvent evt) throws Exception {//GEN-FIRST:event_botonIgualActionPerformed
        // TODO add your handling code here:
        
        
        comp= new Compilador();
        StringTokenizer lexemas = comp.analisisLexico(cadenaAnalisis);
        CompositeEA nodo = comp.arbolDeAnalisisSintactico(lexemas);
        double resultado = nodo.evalua();
        etiquetaNumeros.setText(String.format("% .2f", resultado ));

        



    }//GEN-LAST:event_botonIgualActionPerformed

    //Método que representa el boton del operador √
    private void botonRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRaizActionPerformed
        if(etiquetaNumeros.getText().equals("0")){
           cadenaNumeros = "√ ";
           cadenaAnalisis = "r";
       }else{
             cadenaNumeros += "√ ";
             cadenaAnalisis += "r";
       }
         etiquetaNumeros.setText(cadenaNumeros);
         activado = true;// TODO add your handling code here:
    }//GEN-LAST:event_botonRaizActionPerformed

    //Método que representa el boton del operador /
    private void botonDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDivisionActionPerformed
        if(etiquetaNumeros.getText().equals("0")){
           cadenaNumeros = "÷";
           cadenaAnalisis = "/";
       }else{
             cadenaNumeros += "÷";
             cadenaAnalisis += "/";
       }
         etiquetaNumeros.setText(cadenaNumeros);
         activado = true;// TODO add your handling code here:
    }//GEN-LAST:event_botonDivisionActionPerformed

    //Método que representa el boton de la operacion seno
    private void botonSenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSenActionPerformed
        if(etiquetaNumeros.getText().equals("0")){
           cadenaNumeros = "sen ";
           cadenaAnalisis = "s";
       }else{
             cadenaNumeros += "sen ";
             cadenaAnalisis += "s";
       }
         etiquetaNumeros.setText(cadenaNumeros);
         activado = true;// TODO add your handling code here:
    }//GEN-LAST:event_botonSenActionPerformed

    //Método que representa el boton de la operacion coseno
    private void botonCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCosActionPerformed
        if(etiquetaNumeros.getText().equals("0")){
           cadenaNumeros = "cos ";
           cadenaAnalisis = "c";
       }else{
             cadenaNumeros += "cos ";
             cadenaAnalisis += "c";
       }
         etiquetaNumeros.setText(cadenaNumeros);
         activado = true;// TODO add your handling code here:
    }//GEN-LAST:event_botonCosActionPerformed

    //Método que representa el boton de la operacion tangente
    private void botonTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTanActionPerformed
        if(etiquetaNumeros.getText().equals("0")){
           cadenaNumeros = "tan ";
           cadenaAnalisis = "t";
       }else{
             cadenaNumeros += "tan ";
             cadenaAnalisis += "t";
       }
         etiquetaNumeros.setText(cadenaNumeros);
         activado = true;// TODO add your handling code here:
    }//GEN-LAST:event_botonTanActionPerformed

    //Método que representa el boton del operador *
    private void botonMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMultiplicarActionPerformed
        if(etiquetaNumeros.getText().equals("0")){
           cadenaNumeros = " ×";
           cadenaAnalisis = "*";
       }else{
             cadenaNumeros += " ×";
             cadenaAnalisis += "*";
       }
         etiquetaNumeros.setText(cadenaNumeros);
         activado = true;// TODO add your handling code here:
    }//GEN-LAST:event_botonMultiplicarActionPerformed

    //Método que representa el boton del operador -
    private void botonRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRestaActionPerformed
        if(etiquetaNumeros.getText().equals("0")){
           cadenaNumeros = "-";
           cadenaAnalisis = "-";
           
       }else{
             cadenaNumeros += "-";
             cadenaAnalisis += "-";
       }
         etiquetaNumeros.setText(cadenaNumeros);
         activado = true;// TODO add your handling code here:
    }//GEN-LAST:event_botonRestaActionPerformed

    //Método que representa el boton del operador  parentesis derecho "("
    private void botonParenDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonParenDerActionPerformed
        if(etiquetaNumeros.getText().equals("0")){
           cadenaNumeros = ")";
           cadenaAnalisis = ")";
       }else{
             cadenaNumeros += ")";
             cadenaAnalisis += ")";
       }
         etiquetaNumeros.setText(cadenaNumeros);
         activado = true;// TODO add your handling code here:
    }//GEN-LAST:event_botonParenDerActionPerformed

    //Método que representa el boton de punto
    private void botonPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPuntoActionPerformed
        if(etiquetaNumeros.getText().equals("0")){
           cadenaNumeros = ".";
           cadenaAnalisis = ".";
       }else{
             cadenaNumeros += ".";
             cadenaAnalisis += ".";
       }
         etiquetaNumeros.setText(cadenaNumeros);
         activado = true;// TODO add your handling code here:
    }//GEN-LAST:event_botonPuntoActionPerformed

    //Método que representa el boton del operador  parentesis izquierdo ")"
    private void botonParenIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonParenIzqActionPerformed
        if(etiquetaNumeros.getText().equals("0")){
           cadenaNumeros = "(";
           cadenaAnalisis = "(";
       }else{
             cadenaNumeros += "(";
             cadenaAnalisis += "(";
       }
         etiquetaNumeros.setText(cadenaNumeros);
         activado = true;// TODO add your handling code here:
    }//GEN-LAST:event_botonParenIzqActionPerformed

    //Método que representa el boton que borra el ultimo simbolo que se digita en la calculadora.
    private void botonCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCEActionPerformed
        int tamano = cadenaNumeros.length();
        if (tamano > 0){
             if(tamano == 1){
                 cadenaNumeros = "0";
                 cadenaAnalisis="0";
             }else{
                 cadenaNumeros = cadenaNumeros.substring(0,cadenaNumeros.length()-1);
                 cadenaAnalisis = cadenaAnalisis.substring(0,cadenaAnalisis.length()-1);
                 
             }
             etiquetaNumeros.setText(cadenaNumeros);
        }// TODO add your handling code here:
    }//GEN-LAST:event_botonCEActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     * Método principal que cacha e imprime en pantalla las excepciones.
     */
    public static void main(String args[]) throws ErrorDeSintaxisException,ErrorAritmeticoException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run()  {
                try{
                new Calculadora().setVisible(true);
                }catch(ErrorDeSintaxisException e){
            }catch( ErrorAritmeticoException e){
            }
       
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton0;
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton4;
    private javax.swing.JButton boton5;
    private javax.swing.JButton boton6;
    private javax.swing.JButton boton7;
    private javax.swing.JButton boton8;
    private javax.swing.JButton boton9;
    private javax.swing.JButton botonC;
    private javax.swing.JButton botonCE;
    private javax.swing.JButton botonCos;
    private javax.swing.JButton botonDivision;
    private javax.swing.JButton botonIgual;
    private javax.swing.JButton botonMultiplicar;
    private javax.swing.JButton botonParenDer;
    private javax.swing.JButton botonParenIzq;
    private javax.swing.JButton botonPunto;
    private javax.swing.JButton botonRaiz;
    private javax.swing.JButton botonResta;
    private javax.swing.JButton botonSen;
    private javax.swing.JButton botonSumar;
    private javax.swing.JButton botonTan;
    private javax.swing.JLabel etiquetaMuestra;
    private javax.swing.JLabel etiquetaNumeros;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
